FROM golang:1.25-alpine AS builder

WORKDIR /app

ARG APP_PKG=./cmd/coinbalance-notifier

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /bin/worker "${APP_PKG}"

FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /
COPY --from=builder /bin/worker /worker
USER nonroot:nonroot
ENTRYPOINT ["/worker"]
